#pragma config(Hubs,  S1, HTServo,  HTMotor,  HTMotor,  none)
#pragma config(Sensor, S1,     ,               sensorI2CMuxController)
#pragma config(Sensor, S2,     HTIRS2,            sensorHiTechnicIRSeeker1200)
#pragma config(Motor,  motorA,          flagWaver,     tmotorNXT, PIDControl, encoder)
#pragma config(Motor,  mtr_S1_C2_1,     motorD,        tmotorTetrix, PIDControl, encoder)
#pragma config(Motor,  mtr_S1_C2_2,     motorE,        tmotorTetrix, PIDControl, encoder)
#pragma config(Motor,  mtr_S1_C3_1,     motorF,        tmotorTetrix, PIDControl, encoder)
#pragma config(Motor,  mtr_S1_C3_2,     motorG,        tmotorTetrix, PIDControl, reversed, encoder)
#pragma config(Servo,  srvo_S1_C1_1,    servo1,               tServoNone)
#pragma config(Servo,  srvo_S1_C1_2,    servo2,               tServoNone)
#pragma config(Servo,  srvo_S1_C1_3,    servo3,               tServoNone)
#pragma config(Servo,  srvo_S1_C1_4,    servo4,               tServoNone)
#pragma config(Servo,  srvo_S1_C1_5,    servo5,               tServoNone)
#pragma config(Servo,  srvo_S1_C1_6,    servo6,               tServoNone)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//
//#include "FTC_Comp_Include.c"
#include "hitechnic-irseeker-v2.h"
#define LiftTgtRate 50
#define LowerTgtRate 50
#define LiftCutoffPos 14400
#include "main.c"
//LiftCutoffPos needs tweaking!!!!


void robotInit(){
	//set servos
	nMotorPIDSpeedCtrl[motorF] = mtrSpeedReg;
	nMotorEncoder[motorF] = 0;
	wait10Msec(100); //Allow for sensor stabilization
}

void err_beep(int err_code)
{
	for(int counter = 1; counter<=err_code; counter++)
	{
		while(bSoundActive){wait1Msec(5);}
		wait10Msec(50);
		PlayTone(440, 50);
	}
}

//void lift_up(int tgt_Height)
//{
//	motor[motorF]=LiftTgtRate;
//	while(nMotorEncoder[motorF]<=LiftCutoffPos){
//		wait1Msec(1);
//	}
//	motor[motorF]=0;
//}

void emergency_die()
{
	err_beep(1);
	StopAllTasks();
}

#if 0
void smoothMoveLiftUp()
{
	motor[motorF]=LiftTgtRate;
	while(nMotorEncoder[motorF]<=LiftCutoffPos){
		wait1Msec(1);
	}
	motor[motorF]=0;
}
#endif
void smoothMoveLiftDown(){
	motor[motorF]=LowerTgtRate;
	while(nMotorEncoder[motorF]>160){wait1Msec(1);
	}
	motor[motorF]=0;
}

void headToIrSeek(){
	int _dirDC = 0;
	int _dirAC = 0;
	int acS1, acS2, acS3, acS4, acS5 = 0;
	tHTIRS2DSPMode _mode = DSP_1200;

	HTIRS2readAllACStrength(HTIRS2, acS1, acS2, acS3, acS4, acS5 );
	while(acS5<244){

		while(HTIRS2readDCDir(HTIRS2)!=5 && HTIRS2readACDir(HTIRS2)!=5){
			motor[motorF]=50;
			motor[motorG]=-50;
		}
		motor[motorF]=50;
		motor[motorG]=50;

	}
	motor[motorF]=0;
	motor[motorG]=50;
}
