#pragma config(Hubs,  S1, HTMotor,  HTMotor,  none,     none)
#pragma config(Sensor, S1,     ,               sensorI2CMuxController)
#pragma config(Motor,  mtr_S1_C1_1,     motorD,        tmotorNormal, openLoop)
#pragma config(Motor,  mtr_S1_C1_2,     motorE,        tmotorNormal, openLoop, reversed)
#pragma config(Motor,  mtr_S1_C2_1,     motorF,        tmotorNormal, PIDControl, encoder)
#pragma config(Motor,  mtr_S1_C2_2,     motorG,        tmotorNormal, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//
#define LiftTgtRate 50
#define LowerTgtRate 50
#define LiftCutoffPos 14400
//LiftCutoffPos needs tweaking!!!!
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

void robotInit(){
  //set servos
  nMotorPIDSpeedCtrl[motorF] = mtrSpeedReg;
  nMotorEncoder[motorF] = 0;
  wait10Msec(100); //Allow for sensor stabilization
}

void err_beep(int err_code)
{
  for(int counter = 1; counter<=err_code; counter++)
  {
    while(bSoundActive){wait1Msec(5);}
    wait10Msec(50);
    PlayTone(440, 50);
  }
}

void lift_up(int tgt_Height)
{
    motor[motorF]=LiftTgtRate;
  while(nMotorEncoder[motorF]<=LiftCutoffPos){
    wait1Msec(1);
  }
  motor[motorF]=0;
}

void emergency_die()
{
  err_beep(1);
  StopAllTasks();
}

void smoothMoveLiftUp()
{
  motor[motorF]=LiftTgtRate;
  while(nMotorEncoder[motorF]<=LiftCutoffPos){
    wait1Msec(1);
  }
  motor[motorF]=0;
}

void smoothMoveLiftDown(){
  motor[motorF]=LowerTgtRate;
  while(nMotorEncoder[motorF]>160){wait1Msec(1);
  }
  motor[motorF]=0;
}
