#pragma config(Hubs,  S1, HTServo,  HTMotor,  HTMotor,  none)
#pragma config(Sensor, S1,     ,               sensorI2CMuxController)
#pragma config(Sensor, S2,     HTIRS2,         sensorHiTechnicIRSeeker1200)
#pragma config(Motor,  mtr_S1_C2_1,     motorD,        tmotorTetrix, PIDControl, encoder)
#pragma config(Motor,  mtr_S1_C2_2,     motorE,        tmotorTetrix, PIDControl, encoder)
#pragma config(Motor,  mtr_S1_C3_1,     motorF,        tmotorTetrix, PIDControl, encoder)
#pragma config(Motor,  mtr_S1_C3_2,     motorG,        tmotorTetrix, PIDControl, reversed, encoder)
#pragma config(Servo,  srvo_S1_C1_1,    servo1,               tServoStandard)
#pragma config(Servo,  srvo_S1_C1_2,    servo2,               tServoNone)
#pragma config(Servo,  srvo_S1_C1_3,    servo3,               tServoNone)
#pragma config(Servo,  srvo_S1_C1_4,    servo4,               tServoNone)
#pragma config(Servo,  srvo_S1_C1_5,    servo5,               tServoNone)
#pragma config(Servo,  srvo_S1_C1_6,    servo6,               tServoNone)
#define TURN_CIRCUMFERENCE 0
#define STEP1_TARGET 0
#define STEP2_TARGET 0
#define RINGONEPOS 0
#define RINGTWOPOS 0
#define TGTTOSECONDRING 0
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

#include "joystickDriver.c"
#include "libRobot.c"
void lift_down(int tgt_Height)
{
	nMotorEncoder[motorF]=0;
	motor[motorF]=-1*LiftTgtRate;
	while(nMotorEncoder[motorF]>=-1*tgt_Height){
		wait1Msec(1);
	}
	motor[motorF]=0;
}

bool sense_ring(){
	//TODO
	return true;
}


void lift_up(int tgt_Height)
{
	nMotorEncoder[motorF]=0;
	motor[motorF]=LiftTgtRate;
	while(nMotorEncoder[motorF]<=tgt_Height){
		wait1Msec(1);
	}
	motor[motorF]=0;
}



void performLeftTurn(){


	nMotorEncoder[motorF]=30;
	nMotorEncoder[motorG]=0;
	while (nMotorEncoder[motorF]<TURN_CIRCUMFERENCE){

	}
	motor[motorF]=0;
	motor[motorG]=0;
}
task main(){
	bool ringtwo_sense;
	bool ringone_sense;
	int raiseSpeed;
	while(true){
		getJoystickSettings(joystick);
		if (joystick.StopPgm){
			nxtDisplayTextLine(2, "Disabled!");
			wait10Msec(5);
			motor[motorD]=0;
			motor[motorE]=0;
			motor[motorF]=0;
			motor[motorG]=0;
			continue;
		}
		if (!joystick.UserMode){
			nxtDisplayTextLine(2, "Autonomous");
			while(!joystick.UserMode){
				nMotorEncoder[motorF]=0;
				nMotorEncoder[motorG]=0;
				motor[motorF]=60;
				motor[motorG]=60;
				while (nMotorEncoder[motorG]<STEP1_TARGET){
				}
				motor[motorF]=0;
				motor[motorG]=0;
				performLeftTurn();//MotorF energized
				while(nMotorEncoder[motorF]<STEP2_TARGET){
				}

				lift_up(RINGONEPOS);
				//sense ring

				motor[motorF]=-10;
				motor[motorG]=-10;

				wait10Msec(50);

				motor[motorF]=0;
				motor[motorG]=0;
				ringone_sense=sense_ring();
				lift_down(RINGONEPOS);
				performLeftTurn();
				performLeftTurn();
				performLeftTurn();
				motor[motorF]=0;
				motor[motorG]=0;
				performLeftTurn();//MotorF energized
				while(nMotorEncoder[motorF]<TGTTOSECONDRING){
					motor[motorF]=50;
					motor[motorG]=50;
				}
				motor[motorF]=0;
				motor[motorG]=0;
				//sense ring
				lift_up(RINGTWOPOS);
				motor[motorF]=-10;
				motor[motorG]=-10;

				wait10Msec(50);

				motor[motorF]=0;
				motor[motorG]=0;
				ringtwo_sense=sense_ring();
				lift_down(RINGTWOPOS);
				//lower arm
				motor[motorF]=-20;
				motor[motorG]=-20;
				//backup
				//turn clockwise 90 degrees
				//sense third pvc pipe
				//move forwards
				//release ring 1
				//backup
				//release ring 2
				//backup
				//lower arm
				//turn clockwise 90 degrees
				//go back to step 2 and repeat



		}}
		else{nxtDisplayTextLine(2, "Teleop");
			while(true){//BEGIN TELEOP
				getJoystickSettings(joystick);
				//motor[motorF] = -1*joystick.joy1_y1;
				//motor[motorG] = -1*joystick.joy1_y2;
				if(joy1Btn(1)){
					motor[motorD]=raiseSpeed;
					motor[motorE]=raiseSpeed;
				}
				if(joy1Btn(3)){
					motor[motorD]=-1*raiseSpeed;
					motor[motorE]=-1*raiseSpeed;
				}
				if((!joy1Btn(1))&&(!joy1Btn(3))){
					motor[motorD]=0;
					motor[motorE]=0;
				}
				if(joy1Btn(2)){
					raiseSpeed=20;
				}
				if(joy1Btn(4)){
					raiseSpeed=60;
				}




			}//END TELEOP



		}
	}
}
void autonomous(){

}

void controlled(){

}
