#pragma config(Hubs,  S1, HTServo,  HTMotor,  HTMotor,  none)
#pragma config(Sensor, S1,     ,               sensorI2CMuxController)
#pragma config(Sensor, S2,     HTIRS2,         sensorHiTechnicIRSeeker1200)
#pragma config(Motor,  mtr_S1_C2_1,     motorD,        tmotorTetrix, PIDControl, encoder)
#pragma config(Motor,  mtr_S1_C2_2,     motorE,        tmotorTetrix, PIDControl, encoder)
#pragma config(Motor,  mtr_S1_C3_1,     motorF,        tmotorTetrix, PIDControl, encoder)
#pragma config(Motor,  mtr_S1_C3_2,     motorG,        tmotorTetrix, PIDControl, reversed, encoder)
#pragma config(Servo,  srvo_S1_C1_1,    servo1,               tServoStandard)
#pragma config(Servo,  srvo_S1_C1_2,    servo2,               tServoNone)
#pragma config(Servo,  srvo_S1_C1_3,    servo3,               tServoNone)
#pragma config(Servo,  srvo_S1_C1_4,    servo4,               tServoNone)
#pragma config(Servo,  srvo_S1_C1_5,    servo5,               tServoNone)
#pragma config(Servo,  srvo_S1_C1_6,    servo6,               tServoNone)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

#include "joystickDriver.c"
#include "libRobot.c"

task main(){
	int raiseSpeed;
	while(true){
		getJoystickSettings(joystick);
		if (joystick.StopPgm){
			nxtDisplayTextLine(2, "Disabled!");
			wait10Msec(5);
			motor[motorD]=0;
			motor[motorE]=0;
			motor[motorF]=0;
			motor[motorG]=0;
			continue;
		}
		if (!joystick.UserMode){
			nxtDisplayTextLine(2, "Autonomous");
		}
		else{nxtDisplayTextLine(2, "Teleop");
			while(true){//BEGIN TELEOP
				getJoystickSettings(joystick);
				//motor[motorF] = -1*joystick.joy1_y1;
				//motor[motorG] = -1*joystick.joy1_y2;
				if(joy2Btn(1)){
					motor[motorD]=raiseSpeed;
					motor[motorE]=raiseSpeed;
				}
				if(joy2Btn(3)){
					motor[motorD]=-1*raiseSpeed;
					motor[motorE]=-1*raiseSpeed;
				}
				if((!joy2Btn(1))&&(!joy2Btn(3))){
					motor[motorD]=0;
					motor[motorE]=0;
				}
				if(joy2Btn(2)){
					raiseSpeed=20;
				}
				if(joy2Btn(4)){
					raiseSpeed=60;
				}




			}//END TELEOP



		}
	}
}
void autonomous(){

}

void controlled(){

}
